services:
  postgres:
    image: postgres:16-alpine
    container_name: scanner-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scanner-network
    

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:${REDIS_PORT}"
    networks:
      - scanner-network

  backend:
    build: .
    container_name: scanner-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/app
    networks:
      - scanner-network
    depends_on:
      - redis

networks:
  scanner-network:
    external: true

volumes:
  postgres_data:
